var myString;
var myNum;
var myBool;
var myVar;
// let strArr:string[];
// let numArr:number[];
// let boolean:boolean[];
var strArr;
var boolArr;
var numArr;
boolArr = [true, false, false, true];
strArr = ["chandra", "vinay", "nexgdata"];
numArr = [1, 2, 3, 4., 3];
myString = "Hello".slice(0, 3);
myNum = 25;
myBool = true;
myVar = 1;
var strNumTuple;
strNumTuple = ["hello", 3];
console.log(strNumTuple);
var myVoid = undefined;
var myNull = null;
var myUndifined = undefined;
console.log(myUndifined);
// console.log(boolean);
// console.log(strArr);
// console.log(numArr);
